# Generated by Django 4.2.7 on 2025-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dentista', 'Dentista'), ('secretaria', 'Secretária'), ('admin', 'Admin Sistema')], default='dentista', max_length=20),
        ),
    ]
