# Generated by Django 4.2.7 on 2025-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
