# Generated by Django 4.2.7 on 2025-12-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dentista', 'Dentista'), ('secretaria', 'Secretária'), ('admin', 'Administrador')], default='dentista', max_length=20),
        ),
    ]
