# Generated by Django 4.2.7 on 2025-12-23 02:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, help_text='Vazio para dia todo', null=True)),
                ('hora_fim', models.TimeField(blank=True, help_text='Vazio para dia todo', null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_fim', models.TimeField(default=datetime.time(18, 0))),
                ('intervalo_inicio', models.TimeField(blank=True, default=datetime.time(12, 0), null=True)),
                ('intervalo_fim', models.TimeField(blank=True, default=datetime.time(13, 0), null=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'unique_together': {('dentista', 'dia_semana')},
            },
        ),
    ]
