# Generated by Django 4.2.7 on 2026-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('outro', 'Outro')], default='pendente', max_length=30)),
                ('metodo', models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('outro', 'Outro')], default='outro', max_length=30, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='pacientes/pagamentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
