# Generated by Django 4.2.7 on 2025-12-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='clinic.agendamento'),
        ),
    ]
