# Generated by Django 4.2.7 on 2025-12-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_pagamento_agendamento_alter_pagamento_dentista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('outro', 'Outro')], default='outro', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('outro', 'Outro')], default='pendente', max_length=30),
        ),
    ]
