# Generated by Django 4.2.7 on 2026-01-12 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planotratamento',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_tratamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planotratamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_tratamento', to='clinic.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_medico', to='clinic.paciente'),
        ),
        migrations.AddField(
            model_name='atendimentos',
            name='agendamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='clinic.agendamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='clinic.paciente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='procedimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clinic.procedimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
