# Generated by Django 4.2.7 on 2026-01-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='duracao_estimada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('faltou', 'Faltou'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='atendimentos',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('faltou', 'Faltou'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='agendada', max_length=20),
        ),
    ]
