# Generated by Django 4.2.7 on 2025-12-17 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0003_paciente_cep_paciente_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_tratamento', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_tratamento', to='clinic.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('condicoes_medicas', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_medico', to='clinic.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('tratamento_realizado', models.TextField()),
                ('proximo_passos', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='clinic.agendamento')),
            ],
        ),
    ]
