# Generated by Django 4.2.7 on 2025-12-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_planotratamento_historicomedico_atendimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
