# Generated by Django 4.2.7 on 2025-12-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_agendamento_data_hora_fim_procedimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
    ]
