# Generated by Django 4.2.7 on 2025-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_procedimento_atualizado_em_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
