# Generated by Django 4.2.7 on 2025-12-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_agendamento_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentos',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
    ]
