# Generated by Django 4.2.7 on 2026-01-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='pacientes/documentos/')),
                ('tipo', models.CharField(choices=[('exame', 'Exame'), ('raio_x', 'Raio-X'), ('foto', 'Foto'), ('documento', 'Documento Geral'), ('comprovante', 'Comprovante de Pagamento')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='clinic.agendamento')),
            ],
        ),
    ]
