# Generated by Django 4.2.7 on 2025-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pacientes/documentos/')),
                ('tipo', models.CharField(choices=[('exame', 'Exame'), ('raio_x', 'Raio-X'), ('foto', 'Foto'), ('documento', 'Documento Geral'), ('comprovante', 'Comprovante de Pagamento')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
