# Generated by Django 4.2.7 on 2025-12-16 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_agendamento_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pacientes/documentos/')),
                ('tipo', models.CharField(choices=[('exame', 'Exame'), ('raio_x', 'Raio-X'), ('foto', 'Foto'), ('documento', 'Documento Geral'), ('comprovante', 'Comprovante de Pagamento')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='clinic.agendamento')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clinic.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientDocument',
        ),
    ]
